#!/usr/bin/env node
'use strict';

const cote = require('cote');
const chalk = require('chalk');
const Table = require('cli-table');

const utils = require('../utils/checks');

utils.exitIfArbitratorNotStarted();

const requester = new cote.Requester(
    { name: 'List requester' },
    { log: false }
);

requester.send({ type: 'tell me all' }, objects => {
    const keys = Object.keys(objects);

    if (keys.length === 0) {
        console.info('No daemons running');
        process.exit();
    }

    const blue = s => chalk.blue(s);
    const head = ['Name', 'Path', 'Repository'].map(blue);
    const table = new Table({ head });

    for (let name of keys) {
        const obj = objects[name];
        table.push([name, obj.path, obj.repo]);
    }

    console.log(table.toString());
    process.exit();
});
