#!/usr/bin/env node
'use strict';

const cote = require('cote');
const blue = require('chalk')['blue'];
const table = new require('cli-table')();

const requester = new cote.Requester(
    { name: 'List requester' },
    { log: false }
);

requester.send({ type: 'tell me all' }, objects => {
    const empty = Object.keys(objects).length === 0;

    table.push(['Name', 'Path', 'Repository'].map(blue));
    for (let name in Object.keys(objects)) {
        const obj = objects[name];
        table.push([name, obj.path, obj.repo]);
    }

    console.log(empty ? 'No daemons running' : table.toString());
    process.exit();
});
