#!/usr/bin/env node
'use strict';

const cote = require('cote');
const async = require('async');
const program = require('commander');

const checks = require('../utils/checks');

program.parse(process.argv);

if (program.args.length === 0) {
    return console.error('No names to kill');
}

checks.exitIfArbitratorNotStarted();

const requester = new cote.Requester(
    { name: 'Kill requester', key: 'arbitration' },
    { log: false }
);

async.each(program.args, (name, cb) => {
    requester.send({ type: 'kill please', name }, res => {
        console.info(`Trying to kill: ${name}, result: ${res}`);
        cb();
    });
}, () => process.exit());
