#!/usr/bin/env node
'use strict';

const path = require('path');
const program = require('commander');
const forever = require('forever-monitor');

const servicesDir = path.join(__dirname, '../services/');

program.option('--remote, -r', 'Remote repository for store files')
    .parse(process.argv);

const paths = program.args;

if (paths.length > 1) {
    console.error('Only one path is possible');
    process.exit(1);
}

if (!program.remote) {
    console.error('Please provide remote repository');
    process.exit(1);
}

const watchPath = paths[0];
const repository = program.remote;
console.info(`Running daemon in directory: ${watchPath} 
              Mapped to remote: ${repository}\n`);

// TODO: арбитраж должен быть запущен и только один
const fsServicePath = path.join(servicesDir, 'file-system.js');
new forever.Monitor(fsServicePath, {
    args: [watchPath, repository]
}).start();

console.info('OK!');
