#!/usr/bin/env node
'use strict';

const chalk = require('chalk');
const prompt = require('prompt');

prompt.message = chalk['blue']("etfile");
prompt.start();

prompt.get({
    properties: {
        commitFrequency: {
            description: 'Frequency of commits to remote repository',
            type: 'integer',
            default: 1
        },
        pushFrequency: {
            description: 'Frequency of commits to remote repository',
            type: 'integer',
            default: 10
        },
        needSquash: {
            description: 'Squash all commits into one',
            type: 'boolean',
            default: true
        }
    }
}, (err, result) => {
    if (result) {
        // TODO: Run arbitrator
        console.log(result);
    }
});
